import type { CanonicalEhrState } from "./types";

export const CURRENT_USER_ID = "usr-lena-ortiz";
export const BILLER_USER_ID = "usr-maya-biller";
export const ORG_ID = "org-thera-colorado";

const now = "2026-04-28T12:00:00.000Z";

export const canonicalSeed: CanonicalEhrState = {
  organizations: [
    {
      id: ORG_ID,
      legal_name: "Therassistant Behavioral Health PLLC",
      dba_name: "Therassistant",
      npi: "1234567893",
      tax_id_last4: "4821",
      taxonomy_code: "101YM0800X",
      address_line1: "1700 Lincoln St",
      address_line2: "Suite 2200",
      city: "Denver",
      state: "CO",
      zip: "80203",
      phone: "(720) 555-0100",
      billing_provider_name: "Therassistant Behavioral Health PLLC",
      billing_provider_npi: "1234567893",
      created_at: now,
      updated_at: now,
    },
  ],
  users: [
    {
      id: "usr-lena-ortiz",
      organization_id: ORG_ID,
      full_name: "Lena Ortiz",
      email: "lena.ortiz@therassistant.example",
      role: "clinician",
      credentials: "LPC",
      npi: "1447382111",
      taxonomy_code: "101YP2500X",
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "usr-noah-kim",
      organization_id: ORG_ID,
      full_name: "Noah Kim",
      email: "noah.kim@therassistant.example",
      role: "clinician",
      credentials: "LCSW",
      npi: "1447382222",
      taxonomy_code: "1041C0700X",
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "usr-maya-biller",
      organization_id: ORG_ID,
      full_name: "Maya Chen",
      email: "maya.chen@therassistant.example",
      role: "biller",
      credentials: "CPC",
      npi: "",
      taxonomy_code: "",
      is_active: true,
      created_at: now,
      updated_at: now,
    },
  ],
  patients: [
    {
      id: "pat-avery",
      organization_id: ORG_ID,
      first_name: "Avery",
      middle_name: "",
      last_name: "Morgan",
      preferred_name: "Avery",
      dob: "1998-07-14",
      sex_at_birth: "F",
      gender_identity: "Nonbinary",
      pronouns: "they/them",
      phone: "(720) 555-0142",
      email: "avery.morgan@example.com",
      address_line1: "1430 N Clarkson St",
      address_line2: "",
      city: "Denver",
      state: "CO",
      zip: "80218",
      emergency_contact_name: "Morgan Reed",
      emergency_contact_phone: "(720) 555-9871",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "pat-sofia",
      organization_id: ORG_ID,
      first_name: "Sofia",
      middle_name: "",
      last_name: "Martinez",
      preferred_name: "Sofia",
      dob: "2010-11-03",
      sex_at_birth: "F",
      gender_identity: "Female",
      pronouns: "she/her",
      phone: "Guardian: (303) 555-0178",
      email: "guardian.martinez@example.com",
      address_line1: "8801 E Iliff Ave",
      address_line2: "",
      city: "Denver",
      state: "CO",
      zip: "80231",
      emergency_contact_name: "Elena Martinez",
      emergency_contact_phone: "(303) 555-0178",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "pat-marcus",
      organization_id: ORG_ID,
      first_name: "Marcus",
      middle_name: "",
      last_name: "Thompson",
      preferred_name: "Marcus",
      dob: "1982-02-22",
      sex_at_birth: "M",
      gender_identity: "Male",
      pronouns: "he/him",
      phone: "(720) 555-0166",
      email: "marcus.thompson@example.com",
      address_line1: "601 Wadsworth Blvd",
      address_line2: "",
      city: "Lakewood",
      state: "CO",
      zip: "80214",
      emergency_contact_name: "Dana Clark",
      emergency_contact_phone: "(720) 555-0191",
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ],
  payers: [
    {
      id: "payer-co-medicaid",
      payer_name: "Colorado Medicaid",
      payer_type: "medicaid",
      clearinghouse_payer_id: "CO Medicaid",
      office_ally_payer_id: "CO001",
      availity_payer_id: "CO-MCD",
      state: "CO",
      is_active: true,
    },
    {
      id: "payer-anthem-co",
      payer_name: "Anthem Blue Cross Colorado",
      payer_type: "commercial",
      clearinghouse_payer_id: "ANTHEMCO",
      office_ally_payer_id: "ANTCO",
      availity_payer_id: "ANTHEM-CO",
      state: "CO",
      is_active: true,
    },
  ],
  insurance_policies: [
    {
      id: "pol-avery-primary",
      patient_id: "pat-avery",
      payer_id: "payer-co-medicaid",
      priority: 1,
      member_id: "CO123456789",
      group_number: "RAE3",
      plan_name: "Colorado Medicaid RAE 3",
      subscriber_first_name: "Avery",
      subscriber_last_name: "Morgan",
      subscriber_dob: "1998-07-14",
      subscriber_relationship: "self",
      effective_date: "2026-01-01",
      termination_date: null,
      policy_status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "pol-sofia-primary",
      patient_id: "pat-sofia",
      payer_id: "payer-anthem-co",
      priority: 1,
      member_id: "ABC992120",
      group_number: "CO-EMP",
      plan_name: "Anthem PPO Colorado",
      subscriber_first_name: "Elena",
      subscriber_last_name: "Martinez",
      subscriber_dob: "1980-04-11",
      subscriber_relationship: "child",
      effective_date: "2026-01-01",
      termination_date: null,
      policy_status: "active",
      created_at: now,
      updated_at: now,
    },
  ],
  eligibility_checks: [
    {
      id: "elig-avery-001",
      patient_id: "pat-avery",
      insurance_policy_id: "pol-avery-primary",
      payer_id: "payer-co-medicaid",
      service_type_code: "98",
      request_control_number: "270-AVERY-001",
      response_control_number: "271-AVERY-001",
      eligibility_status: "active",
      copay_amount: 0,
      deductible_amount: 0,
      deductible_remaining: 0,
      coinsurance_percent: 0,
      effective_date: "2026-01-01",
      termination_date: null,
      raw_270: { transaction: "270", serviceType: "98" },
      raw_271: { transaction: "271", status: "active" },
      checked_at: "2026-04-28T08:00:00.000Z",
      checked_by: "usr-maya-biller",
    },
  ],
  appointments: [
    {
      id: "appt-avery-today",
      organization_id: ORG_ID,
      patient_id: "pat-avery",
      clinician_id: "usr-lena-ortiz",
      location_id: null,
      scheduled_start: "2026-04-28T10:00:00.000Z",
      scheduled_end: "2026-04-28T10:53:00.000Z",
      appointment_type: "90837 Psychotherapy",
      status: "completed",
      reason_for_visit: "Anxiety and panic symptoms",
      insurance_policy_id: "pol-avery-primary",
      eligibility_check_id: "elig-avery-001",
      created_at: now,
      updated_at: now,
    },
    {
      id: "appt-sofia-future",
      organization_id: ORG_ID,
      patient_id: "pat-sofia",
      clinician_id: "usr-noah-kim",
      location_id: null,
      scheduled_start: "2026-04-29T16:30:00.000Z",
      scheduled_end: "2026-04-29T17:23:00.000Z",
      appointment_type: "90837 Adolescent Therapy",
      status: "scheduled",
      reason_for_visit: "Emotion regulation and school stress",
      insurance_policy_id: "pol-sofia-primary",
      eligibility_check_id: null,
      created_at: now,
      updated_at: now,
    },
  ],
  encounters: [
    {
      id: "enc-avery-001",
      organization_id: ORG_ID,
      patient_id: "pat-avery",
      appointment_id: "appt-avery-today",
      clinician_id: "usr-lena-ortiz",
      supervisor_id: null,
      date_of_service: "2026-04-28",
      start_time: "2026-04-28T10:00:00.000Z",
      end_time: "2026-04-28T10:53:00.000Z",
      duration_minutes: 53,
      place_of_service_code: "10",
      service_location: "Telehealth; client located in Colorado",
      encounter_status: "draft",
      documentation_status: "in_progress",
      billing_status: "hold",
      primary_diagnosis_code: "F41.1",
      medical_necessity_summary: "Anxiety symptoms continue to impair work functioning and sleep. Psychotherapy is medically necessary to reduce panic symptoms and improve functioning.",
      created_at: now,
      updated_at: now,
    },
  ],
  clinical_notes: [
    {
      id: "note-avery-001",
      encounter_id: "enc-avery-001",
      note_type: "progress",
      note_format: "dap",
      subjective: "Client reported reduced panic frequency and increased confidence using paced breathing. Workplace stress remains a trigger.",
      objective: "Client was alert, oriented, engaged, and able to identify cognitive distortions.",
      assessment: "Symptoms improving but remain clinically significant. No current SI/HI reported.",
      plan: "Continue CBT thought record practice and one values-based exposure before next session.",
      interventions: "CBT cognitive restructuring, grounding skills, exposure planning, psychoeducation.",
      client_response: "Client participated actively and reported skills felt usable outside session.",
      risk_assessment: "Denied current suicidal ideation, homicidal ideation, intent, or plan. Protective factors include partner support and treatment engagement.",
      progress_toward_goals: "Panic frequency reduced from 4x/week to 2x/week. Social connection goal partially addressed.",
      next_steps: "Review exposure practice and sleep routine next week.",
      signed_by: null,
      signed_at: null,
      locked: false,
      created_at: now,
      updated_at: now,
    },
  ],
  encounter_diagnoses: [
    {
      id: "dx-avery-001",
      encounter_id: "enc-avery-001",
      diagnosis_code: "F41.1",
      diagnosis_description: "Generalized anxiety disorder",
      diagnosis_order: 1,
      is_primary: true,
    },
    {
      id: "dx-avery-002",
      encounter_id: "enc-avery-001",
      diagnosis_code: "F33.1",
      diagnosis_description: "Major depressive disorder, recurrent, moderate",
      diagnosis_order: 2,
      is_primary: false,
    },
  ],
  encounter_service_lines: [
    {
      id: "esl-avery-001",
      encounter_id: "enc-avery-001",
      code_type: "CPT",
      procedure_code: "90837",
      modifier_1: "95",
      modifier_2: "",
      modifier_3: "",
      modifier_4: "",
      units: 1,
      minutes: 53,
      charge_amount: 165,
      diagnosis_pointer: "A",
      documentation_support_status: "needs_review",
      billing_status: "hold",
      created_at: now,
      updated_at: now,
    },
  ],
  treatment_plans: [
    {
      id: "tp-avery-001",
      patient_id: "pat-avery",
      organization_id: ORG_ID,
      clinician_id: "usr-lena-ortiz",
      plan_start_date: "2026-01-08",
      plan_review_date: "2026-05-08",
      status: "active",
      diagnosis_summary: "GAD and recurrent MDD with functional impairment in work, sleep, and social connection.",
      clinical_summary: "Treatment uses CBT, grounding skills, behavioral activation, and exposure planning.",
      signed_at: "2026-01-08T18:00:00.000Z",
      created_at: now,
      updated_at: now,
    },
  ],
  treatment_plan_goals: [
    {
      id: "goal-avery-001",
      treatment_plan_id: "tp-avery-001",
      goal_text: "Reduce panic frequency from 4x/week to 1x/week.",
      objective_text: "Client will use grounding and cognitive restructuring during panic triggers.",
      intervention_text: "CBT, exposure hierarchy, paced breathing.",
      target_date: "2026-05-08",
      status: "active",
    },
    {
      id: "goal-avery-002",
      treatment_plan_id: "tp-avery-001",
      goal_text: "Increase social connection and routine.",
      objective_text: "Client will complete one values-based activity each week.",
      intervention_text: "Behavioral activation and values work.",
      target_date: "2026-05-08",
      status: "active",
    },
  ],
  encounter_treatment_plan_links: [
    {
      id: "etp-avery-001",
      encounter_id: "enc-avery-001",
      treatment_plan_id: "tp-avery-001",
      goal_id: "goal-avery-001",
    },
  ],
  claims: [],
  claim_service_lines: [],
  claim_submissions: [],
  claim_status_events: [],
  era_files: [],
  era_claim_payments: [],
  era_line_payments: [],
  claim_adjustments: [],
  workqueue_items: [
    {
      id: "wq-doc-001",
      organization_id: ORG_ID,
      patient_id: "pat-avery",
      encounter_id: "enc-avery-001",
      claim_id: null,
      professional_claim_id: null,
      payer_id: "payer-co-medicaid",
      queue_type: "documentation_hold",
      priority: "normal",
      status: "open",
      title: "Encounter documentation in progress",
      description: "Clinical note is not signed yet. Claim creation is blocked until documentation is signed and service line support is verified.",
      assigned_to: "usr-lena-ortiz",
      due_date: "2026-04-29",
      defer_until: null,
      resolution_note: null,
      created_at: now,
      updated_at: now,
    },
  ],
  workqueue_events: [
    {
      id: "wqe-doc-001",
      workqueue_item_id: "wq-doc-001",
      event_type: "created",
      note: "Documentation hold created from encounter draft.",
      created_by: "usr-lena-ortiz",
      created_at: now,
    },
  ],
  support_tickets: [],
  ticket_messages: [],
  audit_logs: [
    {
      id: "audit-001",
      organization_id: ORG_ID,
      user_id: "usr-lena-ortiz",
      entity_type: "encounter",
      entity_id: "enc-avery-001",
      action: "create",
      before_data: null,
      after_data: { status: "draft" },
      ip_address: "127.0.0.1",
      user_agent: "seed",
      created_at: now,
    },
  ],
  documents: [
    {
      id: "doc-avery-consent",
      organization_id: ORG_ID,
      patient_id: "pat-avery",
      encounter_id: null,
      claim_id: null,
      document_type: "consent",
      file_url: "#",
      file_name: "Informed Consent - Psychotherapy.pdf",
      uploaded_by: "usr-lena-ortiz",
      created_at: "2026-01-08T12:00:00.000Z",
    },
  ],
};
