// CAQH CORE Phase II SOAP+WSDL envelope for Availity real-time 270/271.
//
// Wire format reference:
//   CAQH CORE Connectivity Rule v2.2.0 (SOAP+WSDL)
//   Availity Real Time EDI Companion Guide v.20250529 §SOAP transport
//   Target endpoint: https://gateway.availity.com:2021/core
//
// The envelope wraps an X12 005010X279A1 payload (generated by
// `generate270.ts`). Required metadata fields per CORE §4.4.1:
//   - PayloadType        (e.g. "X12_270_Request_005010X279A1")
//   - ProcessingMode     ("RealTime" | "Batch")
//   - PayloadID          (UUID — echoed back in the response for correlation)
//   - TimeStamp          (ISO 8601 UTC)
//   - SenderID           (the submitter's CORE ID; for Availity this is the
//                         submitter_id assigned in the connection profile)
//   - ReceiverID         (Availity's CORE ID = "030240928", their D&B)
//   - CORERuleVersion    ("2.2.0")
//   - Payload            (CDATA-wrapped X12)
//
// Security: WS-Security UsernameToken (plaintext password over TLS).

const CORE_RULE_VERSION = "2.2.0";
export const AVAILITY_CORE_RECEIVER_ID = "030240928";
export const AVAILITY_CORE_SOAP_ENDPOINT = "https://gateway.availity.com:2021/core";

export type CorePayloadType =
  | "X12_270_Request_005010X279A1"
  | "X12_271_Response_005010X279A1"
  | "X12_276_Request_005010X212"
  | "X12_277_Response_005010X212"
  // CAQH CORE Eligibility Infrastructure Rule vEB.2.0 §2 — the payer
  // may answer a 270 with a 999 functional acknowledgement instead of
  // a 271 when the inbound transaction set is structurally invalid.
  | "X12_999_Response_005010X231A1";

type CoreProcessingMode = "RealTime" | "Batch";

export interface CoreSoapBuildInput {
  payload: string;
  payloadType: CorePayloadType;
  processingMode?: CoreProcessingMode;
  payloadId: string;
  timestamp?: string;
  senderId: string;
  receiverId?: string;
  username: string;
  password: string;
  coreRuleVersion?: string;
}

export interface CoreSoapBuildResult {
  envelope: string;
  payloadId: string;
  timestamp: string;
}

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export function buildCoreSoapRequest(input: CoreSoapBuildInput): CoreSoapBuildResult {
  const timestamp = input.timestamp ?? new Date().toISOString();
  const processingMode = input.processingMode ?? "RealTime";
  const receiverId = input.receiverId ?? AVAILITY_CORE_RECEIVER_ID;
  const ruleVersion = input.coreRuleVersion ?? CORE_RULE_VERSION;
  const envelope =
    `<soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">\n` +
    `  <soapenv:Header>\n` +
    `    <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" soapenv:mustUnderstand="true">\n` +
    `      <wsse:UsernameToken>\n` +
    `        <wsse:Username>${xmlEscape(input.username)}</wsse:Username>\n` +
    `        <wsse:Password>${xmlEscape(input.password)}</wsse:Password>\n` +
    `      </wsse:UsernameToken>\n` +
    `    </wsse:Security>\n` +
    `  </soapenv:Header>\n` +
    `  <soapenv:Body>\n` +
    `    <ns1:COREEnvelopeRealTimeRequest xmlns:ns1="http://www.caqh.org/SOAP/WSDL/CORERule${ruleVersion}.xsd">\n` +
    `      <PayloadType>${input.payloadType}</PayloadType>\n` +
    `      <ProcessingMode>${processingMode}</ProcessingMode>\n` +
    `      <PayloadID>${xmlEscape(input.payloadId)}</PayloadID>\n` +
    `      <TimeStamp>${timestamp}</TimeStamp>\n` +
    `      <SenderID>${xmlEscape(input.senderId)}</SenderID>\n` +
    `      <ReceiverID>${xmlEscape(receiverId)}</ReceiverID>\n` +
    `      <CORERuleVersion>${ruleVersion}</CORERuleVersion>\n` +
    `      <Payload><![CDATA[${input.payload}]]></Payload>\n` +
    `    </ns1:COREEnvelopeRealTimeRequest>\n` +
    `  </soapenv:Body>\n` +
    `</soapenv:Envelope>`;
  return { envelope, payloadId: input.payloadId, timestamp };
}

export interface CoreSoapParseResult {
  payload: string | null;
  payloadType: string | null;
  payloadId: string | null;
  timestamp: string | null;
  senderId: string | null;
  receiverId: string | null;
  errorCode: string | null;
  errorMessage: string | null;
  soapFaultMessage: string | null;
}

function pluck(xml: string, tag: string): string | null {
  const re = new RegExp(`<(?:[A-Za-z0-9]+:)?${tag}[^>]*>([\\s\\S]*?)</(?:[A-Za-z0-9]+:)?${tag}>`, "i");
  const m = xml.match(re);
  return m ? m[1].trim() : null;
}

function pluckCdataOrText(xml: string, tag: string): string | null {
  const text = pluck(xml, tag);
  if (text === null) return null;
  const cdata = text.match(/^<!\[CDATA\[([\s\S]*?)\]\]>$/);
  if (cdata) return cdata[1];
  return text;
}

/** Extracts the COREEnvelopeRealTimeResponse fields from a SOAP body. */
export function parseCoreSoapResponse(rawResponse: string): CoreSoapParseResult {
  const faultBlock = rawResponse.match(/<(?:[A-Za-z0-9]+:)?Fault[\s\S]*?<\/(?:[A-Za-z0-9]+:)?Fault>/i)?.[0] ?? null;
  const soapFaultMessage = faultBlock
    ? (pluck(faultBlock, "faultstring") ?? pluck(faultBlock, "Text") ?? faultBlock.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim())
    : null;

  return {
    payload: pluckCdataOrText(rawResponse, "Payload"),
    payloadType: pluck(rawResponse, "PayloadType"),
    payloadId: pluck(rawResponse, "PayloadID"),
    timestamp: pluck(rawResponse, "TimeStamp"),
    senderId: pluck(rawResponse, "SenderID"),
    receiverId: pluck(rawResponse, "ReceiverID"),
    errorCode: pluck(rawResponse, "ErrorCode"),
    errorMessage: pluck(rawResponse, "ErrorMessage"),
    soapFaultMessage,
  };
}

/** Pull the X12 payload from a CORE SOAP response, falling back to raw scan. */
export function extractX12FromSoap(rawResponse: string): string | null {
  const parsed = parseCoreSoapResponse(rawResponse);
  if (parsed.payload) return parsed.payload.trim();
  const isaMatch = rawResponse.match(/ISA[\s\S]*?IEA\*\d+\*\d+~/);
  return isaMatch ? isaMatch[0] : null;
}
