export type Json = unknown;

type GenericTable = {
  Row: Record<string, unknown>;
  Insert: Record<string, unknown>;
  Update: Record<string, unknown>;
  Relationships: [];
};

type TableDef<Row extends Record<string, unknown>> = {
  Row: Row;
  Insert: Partial<Row>;
  Update: Partial<Row>;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      claims: TableDef<{
          id: string;
          organization_id: string;
          client_id: string | null;
          encounter_id: string | null;
          insurance_policy_id: string | null;
          claim_number: string | null;
          claim_status: string | null;
          total_charge_amount: number | string | null;
          date_of_service_from: string | null;
          date_of_service_to: string | null;
          claim_frequency_code: string | null;
          duplicate_detection_key: string | null;
          ready_to_submit_at: string | null;
          submitted_at: string | null;
          patient_responsibility_amount: number | string | null;
          payer_responsibility_amount: number | string | null;
          paid_at: string | null;
          updated_at: string | null;
          created_at: string | null;
          archived_at: string | null;
        }>;
      eligibility_checks: TableDef<{
          id: string;
          organization_id: string;
          client_id: string;
          appointment_id: string | null;
          insurance_policy_id: string | null;
          clearinghouse_connection_id: string | null;
          edi_270_transaction_id: string | null;
          edi_271_transaction_id: string | null;
          eligibility_status: string | null;
          payer_name: string | null;
          payer_id: string | null;
          service_type_code: string | null;
          plan_name: string | null;
          member_id: string | null;
          subscriber_name: string | null;
          coverage_start_date: string | null;
          coverage_end_date: string | null;
          copay_amount: number | null;
          deductible_total: number | null;
          deductible_remaining: number | null;
          coinsurance_percent: number | null;
          out_of_pocket_remaining: number | null;
          raw_response_json: Json | null;
          raw_response_x12: string | null;
          office_ally_transaction_id: string | null;
          response_status_code: string | null;
          response_status_description: string | null;
          raw_benefits: Json | null;
          effective_date: string | null;
          termination_date: string | null;
          checked_at: string | null;
          response_summary: Json | null;
          external_transaction_id: string | null;
          archived_at: string | null;
          created_at: string | null;
          updated_at: string | null;
        }>;
      claim_status_inquiries: TableDef<{
          id: string;
          organization_id: string;
          claim_id: string;
          client_id: string;
          inquiry_status: string;
          clearinghouse_connection_id: string | null;
          edi_276_transaction_id: string | null;
          edi_277_transaction_id: string | null;
          external_transaction_id: string | null;
          duplicate_detection_key: string | null;
          payer_name: string | null;
          payer_id: string | null;
          payer_status_code: string | null;
          payer_status_text: string | null;
          status_category_code: string | null;
          status_code: string | null;
          entity_code: string | null;
          billed_amount: number | string | null;
          paid_amount: number | string | null;
          check_eft_number: string | null;
          finalized_date: string | null;
          raw_status: Json | null;
          response_summary: string | null;
          requested_at: string | null;
          received_at: string | null;
          created_at: string | null;
          updated_at: string | null;
          archived_at: string | null;
        }>;
      edi_transactions: TableDef<{
          id: string;
          organization_id: string;
          client_id: string | null;
          appointment_id: string | null;
          encounter_id: string | null;
          claim_id: string | null;
          clearinghouse_connection_id: string | null;
          transaction_type: string;
          direction: string;
          status: string;
          control_number: string | null;
          correlation_id: string | null;
          request_payload: Json;
          response_payload: Json;
          raw_request: string | null;
          raw_response: string | null;
          parsed_summary: Json;
          error_message: string | null;
          sent_at: string | null;
          received_at: string | null;
          created_at: string | null;
        }>;
      appointments: TableDef<{
          id: string;
          organization_id: string;
          client_id: string | null;
          provider_id: string | null;
          provider_location_id: string | null;
          insurance_policy_id: string | null;
          scheduled_start_at: string | null;
          scheduled_end_at: string | null;
          appointment_status: string | null;
          appointment_type: string | null;
          reason: string | null;
          check_in_at: string | null;
          cancelled_at: string | null;
          cancellation_reason: string | null;
          telehealth_url: string | null;
          updated_at: string | null;
          created_at: string | null;
          archived_at: string | null;
        }>;
      clients: TableDef<{
          id: string;
          organization_id: string;
          first_name: string | null;
          last_name: string | null;
        }>;
      insurance_payers: TableDef<{
          id: string;
          organization_id: string;
          payer_name: string | null;
          payer_id: string | null;
          payer_type: string | null;
          phone: string | null;
          active_flag: boolean | null;
          archived_at: string | null;
          created_at: string | null;
          updated_at: string | null;
        }>;
      insurance_policies: TableDef<{
          id: string;
          organization_id: string;
          client_id: string;
          payer_id: string | null;
          plan_name: string | null;
          subscriber_id: string | null;
          policy_number: string | null;
          priority: number | null;
          active_flag: boolean | null;
          archived_at: string | null;
        }>;
      encounters: TableDef<{
          id: string;
          organization_id: string;
          client_id: string;
          provider_id: string | null;
          appointment_id: string | null;
          encounter_status: string | null;
          service_date: string | null;
          started_at: string | null;
          ended_at: string | null;
          required_billing_fields_complete: boolean | null;
          archived_at: string | null;
          created_at: string | null;
          updated_at: string | null;
        }>;
      clearinghouse_connections: TableDef<{
          id: string;
          organization_id: string;
          vendor: string;
          mode: string | null;
          is_active: boolean;
          created_at: string | null;
        }>;
      clearinghouse_response_events: TableDef<{
          id: string;
          organization_id: string;
          claim_id: string | null;
          client_id: string | null;
          edi_transaction_id: string | null;
          event_type: string;
          severity: string;
          source: string | null;
          title: string;
          message: string | null;
          normalized_code: string | null;
          raw_codes: Json;
          is_resolved: boolean;
          created_at: string | null;
          archived_at: string | null;
        }>;
      workqueue_items: TableDef<{
          id: string;
          organization_id: string;
          source_object_type: string | null;
          source_object_id: string | null;
          client_id: string | null;
          appointment_id: string | null;
          encounter_id: string | null;
          claim_id: string | null;
          priority: "low" | "medium" | "high" | "urgent" | null;
          status: string | null;
          work_type: string | null;
          queue_type: string | null;
          ticket_type: string | null;
          title: string | null;
          description: string | null;
          source: string | null;
          assigned_role: string | null;
          created_by: string | null;
          resolved_by: string | null;
          resolved_at: string | null;
          context_payload: Json | null;
          created_at: string | null;
          updated_at: string | null;
          archived_at: string | null;
        }>;
      payment_import_items: TableDef<{
          id: string;
          organization_id: string;
          batch_id: string | null;
          payment_import_status: string | null;
          imported_item_ref: string | null;
          payment_date: string | null;
          payer_id: string | null;
          claim_id: string | null;
          client_id: string | null;
          payer_name: string | null;
          check_or_eft_number: string | null;
          billed_amount: number | string | null;
          paid_amount: number | string | null;
          patient_responsibility_amount: number | string | null;
          source: string | null;
          service_line_ref: string | null;
          gross_amount: number | string | null;
          adjustment_amount: number | string | null;
          net_amount: number | string | null;
          unapplied_amount: number | string | null;
          posting_ready: boolean | null;
          raw_item_payload: Json | null;
          original_file_name: string | null;
          storage_bucket: string | null;
          storage_path: string | null;
          file_hash: string | null;
          parse_status: string | null;
          parse_error: string | null;
          parsed_at: string | null;
          match_status: string | null;
          match_reason: string | null;
          matched_at: string | null;
          archived_at: string | null;
          created_at: string | null;
          updated_at: string | null;
        }>;
      payment_import_batches: TableDef<{
          id: string;
          organization_id: string;
          import_source: string | null;
          payment_import_status: string | null;
          source_file_name: string | null;
          source_file_hash: string | null;
          imported_at: string | null;
          total_item_count: number | null;
          total_amount: number | null;
          parse_errors_count: number | null;
          created_at: string | null;
          updated_at: string | null;
        }>;
      payment_postings: TableDef<{
          id: string;
          organization_id: string;
          payment_import_item_id: string;
          posting_status: string | null;
          posting_reference: string | null;
          total_posted_amount: number | string | null;
          note: string | null;
          posted_at: string | null;
          archived_at: string | null;
          created_at: string | null;
          updated_at: string | null;
        }>;
      payment_posting_allocations: TableDef<{
          id: string;
          organization_id: string;
          payment_posting_id: string;
          claim_service_line_id: string | null;
          allocated_amount: number | string | null;
          adjustment_amount: number | string | null;
          patient_responsibility_amount: number | string | null;
          created_at: string | null;
          updated_at: string | null;
        }>;
      encounter_notes: TableDef<{
          id: string;
          organization_id: string;
          encounter_id: string;
          status: string | null;
          signed_at: string | null;
          created_at: string | null;
          provider_id: string | null;
          client_id: string | null;
          archived_at: string | null;
        }>;
      clinical_notes: TableDef<{
          id: string;
          encounter_id: string;
          note_type: string | null;
          note_format: string | null;
          subjective: string | null;
          objective: string | null;
          assessment: string | null;
          plan: string | null;
          interventions: string | null;
          client_response: string | null;
          risk_assessment: string | null;
          progress_toward_goals: string | null;
          next_steps: string | null;
          signed_by: string | null;
          signed_at: string | null;
          locked: boolean | null;
          created_at: string | null;
          updated_at: string | null;
        }>;
      encounter_diagnoses: TableDef<{
          id: string;
          encounter_id: string;
          diagnosis_code: string | null;
          diagnosis_description: string | null;
          diagnosis_order: number | null;
          is_primary: boolean | null;
        }>;
      encounter_service_lines: TableDef<{
          id: string;
          organization_id: string | null;
          encounter_id: string;
          code_type: string | null;
          procedure_code: string | null;
          service_date: string | null;
          sequence_number: number | null;
          cpt_hcpcs_code: string | null;
          units: number | null;
          minutes: number | null;
          charge_amount: number | string | null;
          place_of_service_code: string | null;
          rendering_provider_id: string | null;
          diagnosis_pointer: string | null;
          modifier_1: string | null;
          modifier_2: string | null;
          modifier_3: string | null;
          modifier_4: string | null;
          documentation_support_status: string | null;
          billing_status: string | null;
          created_at: string | null;
          updated_at: string | null;
        }>;
      claim_service_lines: TableDef<{
          id: string;
          organization_id: string | null;
          claim_id: string;
          encounter_service_line_id: string | null;
          line_number: number | null;
          sequence_number: number | null;
          procedure_code: string | null;
          cpt_hcpcs_code: string | null;
          modifiers: string[] | null;
          units: number | null;
          charge_amount: number | string | null;
          service_date: string | null;
          place_of_service_code: string | null;
          line_status: string | null;
          created_at: string | null;
          updated_at: string | null;
        }>;
      claim_submissions: TableDef<{
          id: string;
          organization_id: string | null;
          claim_id: string;
          submission_status: string | null;
          clearinghouse_reference: string | null;
          external_transaction_id: string | null;
          payer_claim_reference: string | null;
          submission_sequence: number | null;
          duplicate_detection_key: string | null;
          response_summary: string | null;
          submitted_at: string | null;
          acknowledged_at: string | null;
          created_at: string | null;
          updated_at: string | null;
          archived_at: string | null;
        }>;
      claim_status_events: TableDef<{
          id: string;
          claim_id: string;
          source: string | null;
          transaction_type: string | null;
          status_code: string | null;
          status_description: string | null;
          event_at: string | null;
          raw_event: Json | null;
          created_at: string | null;
        }>;
      audit_logs: TableDef<{
          id: string;
          organization_id: string | null;
          patient_id: string | null;
          appointment_id: string | null;
          encounter_id: string | null;
          claim_id: string | null;
          clinical_note_id: string | null;
          workqueue_item_id: string | null;
          event_type: string | null;
          event_summary: string | null;
          event_metadata: Json | null;
          created_at: string | null;
        }>;
      [key: string]: GenericTable;
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
